### ISSUE TITLE
python scripts/get_labels.py --source ./ABSK

### ISSUE THREAD

**Issue by y1b2h3** [VlSomers/bpbreid#21]
**Hello, author; Can you help me solve this problem？**

(bpbreid1) D:\downloads\bpbreid-main>python scripts/get_labels.py --source ./ABSK      
* OpenPifPaf model ->  shufflenetv2k16
Processing: 0batch [00:00, ?batch/s]
* MaskRCNN model ->  COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
Processing:   0%|                                                                                                                                                                                           | 0/130 [00:00<?, ?batch/s]D
:\Anaconda\envs\bpbreid1\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Processing:   2%|████                                                                                                                                                                             | 3/130 [04:35<3:15:13, 92.23s/batch]Traceback (most recent call last):
  File "D:\downloads\bpbreid-main\scripts\get_labels.py", line 521, in <module>
    main()
  File "D:\downloads\bpbreid-main\scripts\get_labels.py", line 517, in main
    mask_model(imagery=img_paths, dataset_dir=args.source, is_overwrite=False)
  File "D:\downloads\bpbreid-main\scripts\get_labels.py", line 392, in __call__
    pifpaf_filtered: List[np.ndarray] = self.__filter_pifpaf_with_mask(batch, pifpaf_file_paths)
  File "D:\downloads\bpbreid-main\scripts\get_labels.py", line 475, in __filter_pifpaf_with_mask
    masks = filter_masks(self.model(batch))
  File "D:\downloads\bpbreid-main\scripts\get_labels.py", line 444, in filter_masks
    filtered_boxes, filtered_masks = zip(
ValueError: not enough values to unpack (expected 2, got 0)
Processing:   2%|████                                                                                                              3/130 [06:06<4:18:55, 122.32s/batch]

**Comment by y1b2h3** [comment]
Hello, author. Can I change the dataset from human to animal? How should I operate or modify it？ about get_label.py

**Comment by VlSomers** [comment]
Hi @y1b2h3, to use on an animal dataset, you should first generate the animal parsing labels for your animal dataset using a Pifpaf model trained on another dataset with similar animals (or the same dataset). You should use that animal PifPaf model within the script provided by @samihormi (have a look at the README). You can also create the parsing labels using any other strategies, for instance using SAM or even doing it manually. Then you should create a Torchreid dataset class for your new dataset by replicating what was done for the other ReID datasets (you can have a look at how it's done for OccludedDuke in 'torchreid/data/datasets/image/occluded_dukemtmc.py' for instance).

**Comment by y1b2h3** [comment]
Thank you for your answer. May I also ask if I can use your code for animal identification? If possible, could you give me a rough idea of how to modify it? I have now trained my animal dataset with Openpifpaf. May I know what to do next? Thank you and wish you a happy life!

**Comment by VlSomers** [comment]
Hi @y1b2h3, you can try to run a training with an existing dataset to see how it works, and then create your own subclass of "torchreid/data/datasets/dataset.py" by mimicking what is done in 'torchreid/data/datasets/image/occluded_dukemtmc.py' for instance. Then you should register your dataset in "torchreid/data/datasets/__init__.py". Then in the yaml config you can choose your dataset as source and target:
  sources: ['your_dataset']
  targets: ['your_dataset']
You can also have a look at the official Torchreid documentation for more information:  https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset
Finally, make sure that your images and masks are properly loaded when launching the training, this loading is happening inside "torchreid.data.datasets.dataset.ImageDataset.__getitem__(...)"

**Comment by y1b2h3** [comment]
Thank you very much for your reply again. But when I used my own dataset (cows) for training, I encountered the following issues: 
1、 Do I need to get_ One section of the code '0' in labels. py has been changed to '19' (the corresponding serial number for the cow in the Coco dataset is 19)
Filtered_ Boxes, filtered_ Masks=zip（
       *[(box. cpu(). numpy(), mask. cpu(). numpy()) for box, mask, cls in
       Zip (pre dboxes, pre tasks, pre classes) if cls==0]
2、 If it needs to be modified, after I changed it to 19, I ran the training command and encountered the following error problem. How can I solve it? Looking forward to your reply again. Sincerely thank you

Building model: bpbreid
=> init weights from normal distribution
Loading pretrained ImageNet HRNet32 model at pretrained_models/hrnetv2_w32_imagenet_pretrained.pth
=> loading pretrained model pretrained_models/hrnetv2_w32_imagenet_pretrained.pth
Model complexity: params=34,988,614 flops=8,000,338,432
Building part_based-engine for image-reid
Starting experiment cfa525d2-3942-47ef-823a-cf1195a16acd with job id 587198383 and creation date 2023_08_12_13_02_13_02S
=> Start training
Traceback (most recent call last):
  File "D:\downloads\bpbreid-main\scripts\main.py", line 273, in <module>
    main()
  File "D:\downloads\bpbreid-main\scripts\main.py", line 184, in main
    engine.run(**engine_run_kwargs(cfg))
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 204, in run
    self.train(
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 264, in train
    for self.batch_idx, data in enumerate(self.train_loader):
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 120, in collate
RuntimeError: Trying to resize storage that is not resizable

**Comment by ellzeycunha0** [comment]
@y1b2h3 
I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)".
It is fixed by replacing the version of openpose.
I remember that I also change the the output dim of the model in get_labels.py.
And finally, I get the correct heat map. Thanks for the author's great work.

**Comment by y1b2h3** [comment]
> 我有同样的问题“值错误：没有足够的值来解压缩（预期 2，得到 0）”。它通过替换 openpose 的版本来修复。我记得我还在get_labels.py中更改了模型的输出调暗。最后，我在自己的自定义数据集中获得正确的热图。感谢作者的出色工作。

Hello, friend:
          Thank you very much for your answer
          1. When using a custom dataset, you modified get_ Where are the labels. py files located?
          2. I encountered the following error while using a custom dataset for training. Can you resolve it? Python scripts/main.py -- config file configs/bpbreid/bpbreid_ Absk_ Train.yaml
          
=> Start training
Traceback (most recent call last):
  File "D:\downloads\bpbreid-main\scripts\main.py", line 273, in <module>
    main()
  File "D:\downloads\bpbreid-main\scripts\main.py", line 184, in main
    engine.run(**engine_run_kwargs(cfg))
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 204, in run
    self.train(
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 264, in train
    for self.batch_idx, data in enumerate(self.train_loader):
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 162, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable

**Comment by y1b2h3** [comment]
> @y1b2h3 I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)". It is fixed by replacing the version of openpose. I remember that I also change the the output dim of the model in get_labels.py. And finally, I get the correct heat map in my own custom dataset. Thanks for the author's great work.

Hello, friend:
          Thank you very much for your answer
          1. When using a custom dataset, you modified get_ Where are the labels. py files located?
          2. I encountered the following error while using a custom dataset for training. Can you resolve it? Python scripts/main.py -- config file configs/bpbreid/bpbreid_ Absk_ Train.yaml
          
 => Start training
Traceback (most recent call last):
  File "D:\downloads\bpbreid-main\scripts\main.py", line 273, in <module>
    main()
  File "D:\downloads\bpbreid-main\scripts\main.py", line 184, in main
    engine.run(**engine_run_kwargs(cfg))
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 204, in run
    self.train(
  File "d:\downloads\bpbreid-main\torchreid\engine\engine.py", line 264, in train
    for self.batch_idx, data in enumerate(self.train_loader):
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\Anaconda\envs\bpbreid3\lib\site-packages\torch\utils\data\_utils\collate.py", line 162, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable

**Comment by VlSomers** [comment]
Hi @y1b2h3, the purpose of the collate.py (where you have the error), is to process the output of the dataloader: this error means there's something wrong with the data returned by the dataloader, when building the training batch. The data returned by the dataloader and processed by the collate function comes from the __getitem__(...) function here: "torchreid.data.datasets.dataset.ImageDataset.__getitem__(...)". If you want to solve that error, you have to analyse all the data inside the "sample" object returned by this get_item function and understand what is causing the error: maybe you have an empty array, a wrong data type, or anything else

**Comment by gao1qiang** [comment]
> @y1b2h3 I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)". It is fixed by replacing the version of openpose. I remember that I also change the the output dim of the model in get_labels.py. And finally, I get the correct heat map in my own custom dataset. Thanks for the author's great work.



> @y1b2h3 I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)". It is fixed by replacing the version of openpose. I remember that I also change the the output dim of the model in get_labels.py. And finally, I get the correct heat map in my own custom dataset. Thanks for the author's great work.

Hello friend, I use a custom dataset (not a human) about get_ In addition to modifying the corresponding model, which specific areas do I need to modify in the labels. py file code? I have weak coding skills. Thank you for your kind guidance

**Comment by ellzeycunha0** [comment]
@gao1qiang Give me your email. I would like to share my code and solve your problem.

**Comment by y1b2h3** [comment]
ybh1686362573@163.com   thank  you!

**Comment by gao1qiang** [comment]
ybh1686362573@163.com  thank  you

**Comment by gao1qiang** [comment]
> [ybh1686362573@163.com](mailto:ybh1686362573@163.com) thank you

[ybh1686362573@163.com](mailto:ybh1686362573@163.com) thank you

> @gao1qiang Give me your email. I would like to share my code and solve your problem.

ybh1686362573@163.com               thank you!

**Comment by gao1qiang** [comment]
> @gao1qiang Give me your email. I would like to share my code and solve your problem.

liujinluobite@gmail.com   This account is also available

**Comment by y1b2h3** [comment]
After the training (the custom dataset is not about people), although map and rank indicators were obtained, there were no attention maps of various body parts in my visual heat map  
![1e0604e5b96b9c62dbe2938889c5e8e](https://github.com/VlSomers/bpbreid/assets/116235636/4106564e-f43a-423e-a224-0d4394531d01)

**Comment by gao1qiang** [comment]
After the training (the custom dataset is not about people), although map and rank indicators were obtained, there were no attention maps of various body parts in my visual heat map

![1e0604e5b96b9c62dbe2938889c5e8e](https://github.com/VlSomers/bpbreid/assets/142075205/2aa252ab-fa53-47dd-a6af-2b9e4ce0c246)

**Comment by gao1qiang** [comment]
it is my Query-gallery body part paird distance distance distribution.png.  Why is this happening?
![2cb3d4ffc8d2c29b02b063a0fb09a1a](https://github.com/VlSomers/bpbreid/assets/142075205/760e179d-f417-491e-a0b0-9f3e731f343b)

**Comment by ritaanthem** [comment]
Hi @ellzeycunha0 , I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)".  Could you please share your code to help me solve the problem?

**Comment by ritaanthem** [comment]
> @gao1qiang Give me your email. I would like to share my code and solve your problem.

Hi @ellzeycunha0 , I have the same issue of "ValueError: not enough values to unpack (expected 2, got 0)". Could you please share your code to help me solve the problem?

**Comment by 2541974468** [comment]
Perhaps this file is incorrect? In the code below, a batch of data is passed in, but only the first data item in the batch is processed. Could this processing method be incorrect, meaning that this mask filtering function cannot achieve its intended filtering functionality?
![image](https://github.com/user-attachments/assets/f0596dc6-58cd-491f-a62f-2520b2541df6)
